id: PYSEC-0000-CVE-2022-33124
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: 'AIOHTTP 3.8.1 can report a "ValueError: Invalid IPv6 URL" outcome, which
  can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this
  issue because there is no example of a context in which denial of service would
  occur, and many common contexts have exception handing in the calling application'
affected:
- package:
    name: aiohttp
    ecosystem: PyPI
    purl: pkg:pypi/aiohttp
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/aio-libs/aiohttp/issues/6772
- type: REPORT
  url: https://github.com/aio-libs/aiohttp/issues/6772
aliases:
- CVE-2022-33124
modified: "2023-11-07T03:48:00Z"
published: "2022-06-23T17:15:00Z"
